name: Selenium WebDriver Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium pytest pyperclip

    - name: Run tests
      env:
        DISPLAY: :99
      run: |
        pytest

    - name: Post Test Results
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: ./test-results
